export const SUPABASE_URL = "https://pubfrrwsnfhdmxjmfdhu.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1YmZycndzbmZoZG14am1mZGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4NzI1ODIsImV4cCI6MjA3OTQ0ODU4Mn0.Nf6aNCVUZnPw53g5PyC9CHYpZVEvGwinxh-o22xhNIQ";
export const SUPABASE_SERVICE_ROLE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1YmZycndzbmZoZG14am1mZGh1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mzg3MjU4MiwiZXhwIjoyMDc5NDQ4NTgyfQ.n2w7g8ujLTV5CCi9R0nPpIZ-O7xjQ2hTffGtjlTUg78"

export const RESEND_SUPABASE_URL = "https://hvsxubzgosiopcsmdavl.supabase.co";
export const RESEND_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2c3h1Ynpnb3Npb3Bjc21kYXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDQwODQsImV4cCI6MjA2MjYyMDA4NH0.lcfxCzPaaM8dPv7KncXsEYjTgyXz39EsPZcnyJHRBQ4";

