// export const SUPABASE_URL = "https://pubfrrwsnfhdmxjmfdhu.supabase.co";
// export const SUPABASE_ANON_KEY =
//   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1YmZycndzbmZoZG14am1mZGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4NzI1ODIsImV4cCI6MjA3OTQ0ODU4Mn0.Nf6aNCVUZnPw53g5PyC9CHYpZVEvGwinxh-o22xhNIQ";
// export const SUPABASE_SERVICE_ROLE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1YmZycndzbmZoZG14am1mZGh1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mzg3MjU4MiwiZXhwIjoyMDc5NDQ4NTgyfQ.n2w7g8ujLTV5CCi9R0nPpIZ-O7xjQ2hTffGtjlTUg78"

export const SUPABASE_URL = "https://bokfhubogcuoqcjawaao.supabase.co";
export const SUPABASE_ANON_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJva2ZodWJvZ2N1b3FjamF3YWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MjY4MDksImV4cCI6MjA3OTUwMjgwOX0.5NVzb_xbrTsWXepS8yYTOfa6UlOTdgnfZt84dzlLXDQ"
export const SUPABASE_SERVICE_ROLE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJva2ZodWJvZ2N1b3FjamF3YWFvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzkyNjgwOSwiZXhwIjoyMDc5NTAyODA5fQ.yWAdCwbYh_XQHvJXjQ1SSHdSSy1pjnw9uyLsvYfpQC0"

export const RESEND_API_KEY="re_RJAxrHDH_7EVbnASbeCcSzDY89nokUCKZ"