/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthRequestOtpRouteImport } from './routes/_auth/request-otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthEnterAmountRouteImport } from './routes/_auth/enter-amount'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedAdminUploadParticipantsRouteImport } from './routes/_protected/admin/upload-participants'
import { Route as ProtectedAdminParticipantsRouteImport } from './routes/_protected/admin/participants'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthRequestOtpRoute = AuthRequestOtpRouteImport.update({
  id: '/request-otp',
  path: '/request-otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEnterAmountRoute = AuthEnterAmountRouteImport.update({
  id: '/enter-amount',
  path: '/enter-amount',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminUploadParticipantsRoute =
  ProtectedAdminUploadParticipantsRouteImport.update({
    id: '/upload-participants',
    path: '/upload-participants',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminParticipantsRoute =
  ProtectedAdminParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/enter-amount': typeof AuthEnterAmountRoute
  '/login': typeof AuthLoginRoute
  '/request-otp': typeof AuthRequestOtpRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/admin/participants': typeof ProtectedAdminParticipantsRoute
  '/admin/upload-participants': typeof ProtectedAdminUploadParticipantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/enter-amount': typeof AuthEnterAmountRoute
  '/login': typeof AuthLoginRoute
  '/request-otp': typeof AuthRequestOtpRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/admin/participants': typeof ProtectedAdminParticipantsRoute
  '/admin/upload-participants': typeof ProtectedAdminUploadParticipantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_auth/enter-amount': typeof AuthEnterAmountRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/request-otp': typeof AuthRequestOtpRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/admin/participants': typeof ProtectedAdminParticipantsRoute
  '/_protected/admin/upload-participants': typeof ProtectedAdminUploadParticipantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/enter-amount'
    | '/login'
    | '/request-otp'
    | '/dashboard'
    | '/admin/participants'
    | '/admin/upload-participants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/enter-amount'
    | '/login'
    | '/request-otp'
    | '/dashboard'
    | '/admin/participants'
    | '/admin/upload-participants'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_protected/admin'
    | '/_auth/enter-amount'
    | '/_auth/login'
    | '/_auth/request-otp'
    | '/_protected/dashboard'
    | '/_protected/admin/participants'
    | '/_protected/admin/upload-participants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/request-otp': {
      id: '/_auth/request-otp'
      path: '/request-otp'
      fullPath: '/request-otp'
      preLoaderRoute: typeof AuthRequestOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/enter-amount': {
      id: '/_auth/enter-amount'
      path: '/enter-amount'
      fullPath: '/enter-amount'
      preLoaderRoute: typeof AuthEnterAmountRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/upload-participants': {
      id: '/_protected/admin/upload-participants'
      path: '/upload-participants'
      fullPath: '/admin/upload-participants'
      preLoaderRoute: typeof ProtectedAdminUploadParticipantsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/participants': {
      id: '/_protected/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof ProtectedAdminParticipantsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthEnterAmountRoute: typeof AuthEnterAmountRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRequestOtpRoute: typeof AuthRequestOtpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthEnterAmountRoute: AuthEnterAmountRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRequestOtpRoute: AuthRequestOtpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminParticipantsRoute: typeof ProtectedAdminParticipantsRoute
  ProtectedAdminUploadParticipantsRoute: typeof ProtectedAdminUploadParticipantsRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminParticipantsRoute: ProtectedAdminParticipantsRoute,
  ProtectedAdminUploadParticipantsRoute: ProtectedAdminUploadParticipantsRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
